export const questionsData = [
  {
    id: 1,
    type: "mcq",
    text: "Which HTML tag is used to include JavaScript code?",
    options: ["<js>", "<javascript>", "<script>", "<code>"],
    answer: 2,
  },
  {
    id: 2,
    type: "mcq",
    text: "Which method is used to add an element at the end of an array in JavaScript?",
    options: ["push()", "pop()", "shift()", "unshift()"],
    answer: 0,
  },
  {
    id: 3,
    type: "mcq",
    text: "HTML stands for?",
    options: [
      "Hyper Transfer Markup Language",
      "HyperText Markup Language",
      "HighText Markdown Language",
      "Home Tool Markup Language",
    ],
    answer: 1,
  },
  {
    id: 4,
    type: "mcq",
    text: "Which CSS property sets the text color?",
    options: ["color", "text-color", "font-color", "foreground"],
    answer: 0,
  },
  {
    id: 5,
    type: "mcq",
    text: "typeof null in JavaScript is…?",
    options: ["null", "object", "undefined", "number"],
    answer: 1,
  },
  {
    id: 6,
    type: "mcq",
    text: "Which method converts JSON string to an object?",
    options: [
      "JSON.toObject()",
      "JSON.parse()",
      "Object.fromJSON()",
      "parseJSON()",
    ],
    answer: 1,
  },
  {
    id: 7,
    type: "mcq",
    text: "Make an element a flex container:",
    options: [
      "display: flex;",
      "flex: 1;",
      "position: flex;",
      "justify-content: flex;",
    ],
    answer: 0,
  },
  {
    id: 8,
    type: "mcq",
    text: "Largest HTML heading tag?",
    options: ["<h1>", "<h3>", "<h6>", "<header>"],
    answer: 0,
  },
  {
    id: 9,
    type: "mcq",
    text: "HTTP status for Not Found:",
    options: ["400", "404", "401", "500"],
    answer: 1,
  },
  {
    id: 10,
    type: "mcq",
    text: "Array method that returns a new array of elements passing a test:",
    options: ["map", "filter", "forEach", "reduce"],
    answer: 1,
  },
  {
    id: 11,
    type: "mcq",
    text: "Git command to stage changes:",
    options: ["git commit", "git push", "git add", "git init"],
    answer: 2,
  },
  {
    id: 12,
    type: "mcq",
    text: "Which keyword declares a constant in JavaScript?",
    options: ["var", "let", "const", "define"],
    answer: 2,
  },
  // True/False Questions
  {
    id: 13,
    type: "tf",
    text: "CSS stands for Cascading Style Sheets.",
    correct: true,
  },
  {
    id: 14,
    type: "tf",
    text: "JavaScript can only be run in the browser.",
    correct: false,
  },
  {
    id: 15,
    type: "tf",
    text: "HTML5 introduced the <video> element.",
    correct: true,
  },
  {
    id: 16,
    type: "tf",
    text: "In Git, 'git push' is used to stage files.",
    correct: false,
  },
  {
    id: 17,
    type: "tf",
    text: "JSON stands for JavaScript Object Notation.",
    correct: true,
  },
];
